### PR TITLE
Fixed PCI device listing.

### LINKED ISSUE #129: PCI device definition is wrong
Our current approach to dealing with PCI devices is not good enough.
PCI Device after listing does not know it's own device number and at which bus it is present. This leads to problems with reading device configuration space later in drivers.

Also PCI configuration space is divided into two blocks - 64 bytes are mandatory for all devices, but later additional 192 bytes are available for devices. This additional space is used for device specific configuration. (For example: PCI ATA controller will use some of this space to configure timings).

Things to change:

- [x] - Change current pci_device to pci_configuration_space or something similar.
- [x] - Add new PCI Device that will also contain bus and device numbers.
- [x] - Change current code to use new changes.
- [x] - Possibly retain backwards compatibility with previous functions (W.I.P stage, still figuring out who used what and where).
- [x] - Add configuration space read/write functions for better management.

### PR DESCRIPTION
**Pull request by MinusPL**
Fixes #129
Changes:
* Devices now have bus, device and function IDs
* Redesigned functions to read and write to PCI device configuration space
* Made sure devices return proper values from PCI config space.
* Added missing 192 bytes of device config space as union made of bytes, words and dwords. This region is device dependant.
* Limited reading of PCI config space to 64 bytes for PCI Bridges.
* Removed pci_in_data structure and replace it by pci_cmd_address_reg, which follows PCI specification naming.
* Added documentation for all PCI related functions.

### CODE REVIEW

File: os/kernel/src/drivers/pci/pci.c [hunk 1]
```diff
@@ -4,33 +4,34 @@
 #include <stdlib.h>
 #include <ktime.h>
```
Comment (JakubPrzystasz) [inline os/kernel/src/drivers/pci/pci.c]: Why do you need a ktime?

Comment (MinusPL) [reply os/kernel/src/drivers/pci/pci.c]: huh, it must've been leftover, removing this
Will change pci device listing to not use delays, then I can safely remove ktime

**Review by MatiF100 — APPROVED** [review]
