### PR TITLE
Fix for limited amount of syscalls (Issue #97). Max amount of syscall…

### LINKED ISSUE #97: Extending syscall count to 16 bit value from 8 bit
Currently MicrOS uses 8 bit table for syscalls. Due to development free space for new syscalls is slowly disappearing.
This means we need to extend it to 16 bit values.

Current idea is to change syscall IDs to 16 ushort value (uint16_t) and divide it to two bytes, one for category and one for function in that category.
As for now MicrOS uses 8 bit value divided into two nibbles for group and function.
Extension will allow to use up to 65536 syscalls.

Any ideas as for how to make this change are welcome.

Due to this change please do not create new branches without good reason and focus on finishing up current things in W.I.P state, so you don't have to resolve conflicts in future.

If your branch has to add new syscalls, please leave that information here as comment, so we can assign new group ID for your functions.

PLANNED TIME OF APPLYING CHANGES: January/February 2022.

### PR DESCRIPTION
**Pull request by MinusPL**
Each syscall group has been redefined, compare your changes to new code. If your syscalls are extending group, please change their numbering.
If you are providing new syscall group, please change numbering and use one of free group numbers (usually next one that is free). New format is is 0xZZYY, where ZZ means group number and YY is number of syscall in that group.
In future some group numbers might be freed due to merging of groups with only few syscalls.

Provides fix for Issue #97.

### CODE REVIEW

File: library/src/micros/micros_process.c [hunk 1]
```diff
@@ -2,57 +2,57 @@
...
 uint32_t micros_process_get_processes_count()
 {
-    return micros_interrupt_0a(0x91);
+    return micros_interrupt_0a(0x0701);
 }
 
 void micros_process_get_current_process_info(micros_process_user_info *user_info)
 {
-    micros_interrupt_1a(0x92, (uint32_t)user_info);
+    micros_interrupt_1a(0x7020, (uint32_t)user_info);
```
Comment (MatiF100) [inline library/src/micros/micros_process.c]: Wrong group number. Probably should be 0702 instead of 7020

**Review by MatiF100 — CHANGES_REQUESTED** [review]
Small bug in micros_process.c line 15

**Review by MatiF100 — APPROVED** [review]
